[package]
name = "tremor-kv"
version = "0.5.0"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"
description = "A logstash inspured key value extractor"
readme = "README.md"

[dependencies]
simd-json = { version = "0.10.3" }
serde = "1"

[features]
default = ["known-key"]
known-key = ["simd-json/known-key"]
arraybackend = ["simd-json/arraybackend"]
